import Nav from "@/components/navbar"

import 'bootstrap/dist/css/bootstrap.css'
import '../styles/app.scss'
import Script from "next/script"
import Footer from "./footer"
import { NextSeo } from "next-seo"

export const metadata = {
  title: 'Portfolio TF',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt">
      <body>
        <Nav />
        {children}
      </body>
    </html>
  )
}
